# Generated by Django 6.0.6 on 2026-07-07 11:36

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Category Name')),
            ],
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Dish Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('calories', models.PositiveIntegerField(blank=True, null=True, verbose_name='Calories')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Product Name')),
                ('calories_per_100g', models.PositiveIntegerField(verbose_name='Calories per 100g')),
                ('protein_per_100g', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Protein per 100g')),
                ('fat_per_100g', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Fat per 100g')),
                ('carbs_per_100g', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Carbohydrates per 100g')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='blog.category', verbose_name='Category')),
            ],
        ),
        migrations.CreateModel(
            name='DishIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_grams', models.PositiveIntegerField(verbose_name='Weight in grams')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dishingredients', to='blog.dish')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blog.product')),
            ],
            options={
                'unique_together': {('dish', 'product')},
            },
        ),
        migrations.AddField(
            model_name='dish',
            name='ingridients',
            field=models.ManyToManyField(related_name='dishes', through='blog.DishIngredient', to='blog.product', verbose_name='Ingridients'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('male', 'Чоловіча'), ('female', 'Жіноча')], max_length=10, verbose_name='Gender')),
                ('age', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(100)], verbose_name='Age')),
                ('height_cm', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(250)], verbose_name='Height (cm)')),
                ('weight_kg', models.DecimalField(decimal_places=1, max_digits=5, validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(300)], verbose_name='Weight (kg)')),
                ('activity_level', models.CharField(choices=[('low', 'Низький'), ('medium', 'Середній'), ('high', 'Високий')], default='medium', max_length=10, verbose_name='Рівень активності')),
                ('goal', models.CharField(choices=[('lose', 'Схуднути'), ('maintain', 'Зберегти вагу'), ('gain', 'Набрати вагу')], default='maintain', max_length=10, verbose_name='Goal')),
                ('calculated_daily_norm', models.PositiveIntegerField(blank=True, null=True, verbose_name='Розрахована денна норма')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'User profile',
                'verbose_name_plural': 'Профілі користувачів',
            },
        ),
        migrations.CreateModel(
            name='DiaryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('amount_grams', models.PositiveIntegerField(help_text="Вага з'їденого в грамах (для страви — вага порції)", verbose_name='Кількість (г)')),
                ('calories', models.PositiveIntegerField(help_text='Заповнюється автоматично при збереженні', verbose_name='Розраховані калорії')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diary_entries', to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
                ('dish', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diary_entries', to='blog.dish')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diary_entries', to='blog.product')),
            ],
            options={
                'verbose_name': 'Запис щоденника',
                'verbose_name_plural': 'Записи щоденника',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['user', 'date'], name='blog_diarye_user_id_6f14b0_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('dish__isnull', True), ('product__isnull', False)), models.Q(('dish__isnull', False), ('product__isnull', True)), _connector='OR'), name='diary_entry_exactly_one_of_product_or_dish')],
            },
        ),
    ]
